# config for duom1's dotfiles

title = "dotfile_config"

[ensure_installed]
programs = [
  "git",
  "make",
  "gcc",
  "python3",
  "pkg-config",
  "redshift",
  "xbanish",
  "wget",
  "picom",
  "nitrogen",
  "rofi",
  "sed",
  "maim",
  "xclip",
  "brightnessctl",
  "unzip",
  "perl",
  "pamixer",
  "themix-gui",
  "lxappearance",
  ["pywalfox", "python-pywalfox"],
  ["trash-put", "trash-cli"],
  ["node", "nodejs"],
  ["nvim", "neovim"],
  ["xmodmap", "xorg-xmodmap"],
  ["xset", "xorg-xset"],
  ["xrandr", "xorg-xrandr"],
  ["wal", "pywal"],
]
libs = [
  ["xinerama", "libxinerama"], # "libxinerama-dev"],
  ["xft", "libxft"], # "libxft-dev"],
  ["x11", "libx11"], # "libx11-dev"],
  ["imlib2", "imlib2"],
]

[wallpaper_and_theme]
elementary = { repo = "https://github.com/elementary/wallpapers", install = false }
fonts = { jetbrainsmono = { link = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/JetBrainsMono.zip", name = "JetBrainsMono.zip", enable = true }, enable = false}
  [wallpaper_and_theme.wal]
  wallpaper = "Morskie Oko.jpg"
  enable = true

[suckless]
  [suckless.dwm]
  source = "https://github.com/duom1/dwm"
  enable = true

  [suckless.st]
  source = "https://github.com/duom1/st"
  enable = true

  [suckless.slstatus]
  source = "https://github.com/duom1/slstatus"
  enable = false

  [suckless.slock]
  source = "https://github.com/duom1/slock"
  enable = false

[nvim]
  astronvim = false

[link]
enable = true

  [link.wallpapers]
  source = "./Wallpapers"
  dest = "~/Pictures/Wallpapers"
  enable = true

  [link.bashrc]
  source = "./.bashrc"
  dest = "~/.bashrc"
  enable = true

  [link.xinitrc]
  source = "./.xinitrc"
  dest = "~/.xinitrc"
  enable = true

  [link.redshift]
  source = "./redshift.conf"
  dest = "~/.config/redshift.conf"
  enable = true

  [link.rofi]
  source = "./config.rasi"
  dest = "~/.config/rofi/config.rasi"
  enable = true

  [link.dicord]
  source = "./discord.desktop"
  dest = "~/.local/share/applications/discord.desktop"
  enable = true

  [link.spotify]
  source = "./spotify.desktop"
  dest = "~/.local/share/applications/spotify.desktop"
  enable = true

  [link.forcerate]
  source = "./force-rate.pl"
  dest = "~/force-rate.pl"
  enable = true

  [link.xmodmap]
  source = "./.Xmodmap"
  dest = "~/.Xmodmap"
  enable = true

  [link.getvolume]
  source = "./get-volume.sh"
  dest = "~/get-volume.sh"
  enable = true

  [link.lock]
  source = "./lock.sh"
  dest = "~/lock.sh"
  enable = true

  [link.picom]
  source = "./picom.conf"
  dest = "~/.config/picom.conf"
  enable = true

  [link.powermenu]
  source = "./rofi-power-menu"
  dest = "~/.local/bin/rofi-power-menu"
  enable = true

  [link.neofetch]
  source = "./config.conf"
  dest = "~/.config/neofetch/config.conf"
  enable = true

  [link.walh]
  source = "./walh-default.vim"
  dest = "~/.config/nvim/walh-default.vim"
  enable = true

  [link.discordwal]
  source = "./discord-pywal.css"
  dest = "~/.config/wal/templates/discord-pywal.css"
  enable = false

